Repository Ericgacoki/Markdown_Files, pull requests merged in 2021-02, with the labels that each got.

#9 My Branch
  README.md
Labels: good first issue

#4 My branch
  README.md
  ReadMe.md
Labels: done

#6 My branch
  README.md
Labels: final review, good first issue

#2 My branch
  ReadMe.md
Labels: assigned for review, final review

#1 Update README.md
  README.md
Labels: final review, good first PR

#5 My forked code
  README.md
Labels: final review

#3 Update ReadMe.md
  ReadMe.md
Labels: final review
